# Generated by Django 5.1.4 on 2026-08-03 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Documento"),
                            ("TEXT", "Texto"),
                            ("QUIZ", "Evaluación"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Contenido enriquecido para lecciones de texto."
                    ),
                ),
            ],
            options={
                "verbose_name": "lección",
                "verbose_name_plural": "lecciones",
                "db_table": "lessons",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "módulo",
                "verbose_name_plural": "módulos",
                "db_table": "modules",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.CharField(help_text="Ruta relativa dentro del storage.", max_length=500),
                ),
                ("mime_type", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("PDF", "PDF"),
                            ("DOCX", "Word"),
                            ("PPTX", "PowerPoint"),
                            ("TXT", "Texto plano"),
                            ("MD", "Markdown"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("ANALYZING", "Analizando"),
                            ("AVAILABLE", "Disponible"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=60)),
                ("error_detail", models.TextField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("thumbnail", models.CharField(blank=True, max_length=500)),
                ("language", models.CharField(blank=True, max_length=10)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Resumen ejecutivo generado por la IA."),
                ),
                (
                    "partial_analysis",
                    models.BooleanField(
                        default=False,
                        help_text="El RAG funciona, pero alguna cadena de análisis falló.",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="trainings.lesson",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materiales",
                "db_table": "materials",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="trainings.module",
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("timestamp_seconds", models.FloatField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="trainings.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notes",
                "ordering": ["timestamp_seconds", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=120)),
                ("step", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En ejecución"),
                            ("SUCCESS", "Completada"),
                            ("FAILED", "Fallida"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="trainings.material",
                    ),
                ),
            ],
            options={
                "db_table": "processing_jobs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("slug", models.SlugField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Principiante"),
                            ("INTERMEDIATE", "Intermedio"),
                            ("ADVANCED", "Avanzado"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="trainings/covers/"),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PUBLISHED", "Publicada"),
                            ("ARCHIVED", "Archivada"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("chat_enabled", models.BooleanField(default=True)),
                (
                    "cross_material_search",
                    models.BooleanField(
                        default=False,
                        help_text="Permite que el chat consulte todo el proyecto y no solo esta capacitación.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "capacitación",
                "verbose_name_plural": "capacitaciones",
                "db_table": "trainings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="module",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="trainings.training",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Asignada"),
                            ("IN_PROGRESS", "En curso"),
                            ("COMPLETED", "Completada"),
                            ("EXPIRED", "Vencida"),
                        ],
                        db_index=True,
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("assigned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción",
                "verbose_name_plural": "inscripciones",
                "db_table": "enrollments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField()),
                ("chunk_size", models.PositiveIntegerField()),
                ("received_chunks", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to="trainings.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upload_sessions",
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                ("position_seconds", models.PositiveIntegerField(default=0)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="trainings.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="trainings.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_progress",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "lesson"), name="uq_lesson_progress"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["lesson"], name="idx_material_lesson"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["project", "status"], name="idx_material_project_status"),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "sha256"),
                name="uq_material_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["module", "order"], name="idx_lesson_module_order"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["user", "lesson"], name="idx_note_user_lesson"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["material", "-started_at"], name="idx_job_material"),
        ),
        migrations.AddIndex(
            model_name="training",
            index=models.Index(fields=["project", "status"], name="idx_training_project_status"),
        ),
        migrations.AddConstraint(
            model_name="training",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "slug"),
                name="uq_training_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(fields=["training", "order"], name="idx_module_training_order"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["training", "status"], name="idx_enrollment_status"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["user", "status"], name="idx_enrollment_user"),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(fields=("user", "training"), name="uq_enrollment"),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(fields=["user", "completed"], name="idx_upload_user"),
        ),
    ]
