/** Mapa central de rutas de la API (evita literales dispersos por el código). */

export const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    passwordReset: '/auth/password-reset',
    passwordResetConfirm: '/auth/password-reset/confirm',
  },
  users: {
    list: '/users/',
    detail: (id: string) => `/users/${id}/`,
    activate: (id: string) => `/users/${id}/activate/`,
    deactivate: (id: string) => `/users/${id}/deactivate/`,
    bulkInvite: '/users/bulk-invite/',
    groups: '/user-groups/',
    groupMembers: (id: string) => `/user-groups/${id}/members/`,
  },
  company: '/company',
  projects: {
    list: '/projects/',
    detail: (id: string) => `/projects/${id}/`,
    stats: (id: string) => `/projects/${id}/stats/`,
    members: (id: string) => `/projects/${id}/members/`,
    rebuildIndex: (id: string) => `/projects/${id}/rebuild-index/`,
    vectorCollection: (id: string) => `/projects/${id}/vector-collection/`,
  },
  trainings: {
    list: '/trainings/',
    detail: (id: string) => `/trainings/${id}/`,
    tree: (id: string) => `/trainings/${id}/detail/`,
    publish: (id: string) => `/trainings/${id}/publish/`,
    unpublish: (id: string) => `/trainings/${id}/unpublish/`,
    duplicate: (id: string) => `/trainings/${id}/duplicate/`,
    search: (id: string) => `/trainings/${id}/search/`,
    modules: (id: string) => `/trainings/${id}/modules/`,
    reorderModules: (id: string) => `/trainings/${id}/modules/reorder/`,
    enrollments: (id: string) => `/trainings/${id}/enrollments/`,
    exams: (id: string) => `/trainings/${id}/exams`,
    generateExam: (id: string) => `/exams/generate/${id}/`,
    chatSessions: (id: string) => `/trainings/${id}/chat-sessions`,
    agentRun: (id: string) => `/trainings/${id}/agent/run`,
  },
  modules: {
    detail: (id: string) => `/modules/${id}/`,
    lessons: (id: string) => `/modules/${id}/lessons/`,
    reorderLessons: (id: string) => `/modules/${id}/lessons/reorder/`,
  },
  lessons: {
    detail: (id: string) => `/lessons/${id}/`,
    progress: (id: string) => `/lessons/${id}/progress/`,
    complete: (id: string) => `/lessons/${id}/complete/`,
    notes: (id: string) => `/lessons/${id}/notes/`,
    uploadSession: (id: string) => `/lessons/${id}/materials/upload-session/`,
    uploadMaterial: (id: string) => `/lessons/${id}/materials/`,
  },
  materials: {
    detail: (id: string) => `/materials/${id}/`,
    status: (id: string) => `/materials/${id}/status/`,
    jobs: (id: string) => `/materials/${id}/jobs/`,
    reprocess: (id: string) => `/materials/${id}/reprocess/`,
    stream: (id: string) => `/materials/${id}/stream/`,
    transcript: (id: string) => `/materials/${id}/transcript/`,
    content: (id: string) => `/materials/${id}/content/`,
    chapters: (id: string) => `/materials/${id}/chapters/`,
    concepts: (id: string) => `/materials/${id}/concepts/`,
    faqs: (id: string) => `/materials/${id}/faqs/`,
    uploadChunk: (uploadId: string) => `/materials/uploads/${uploadId}/chunk`,
    uploadComplete: (uploadId: string) => `/materials/uploads/${uploadId}/complete`,
  },
  me: {
    trainings: '/me/trainings',
    trainingDetail: (id: string) => `/me/trainings/${id}`,
    attempts: '/me/attempts',
    stats: '/analytics/me',
    activity: '/analytics/me/activity',
  },
  chat: {
    session: (id: string) => `/chat-sessions/${id}/`,
    messages: (id: string) => `/chat-sessions/${id}/messages/`,
    ask: (id: string) => `/chat-sessions/${id}/ask/`,
    feedback: (sessionId: string, messageId: string) =>
      `/chat-sessions/${sessionId}/messages/${messageId}/feedback/`,
  },
  exams: {
    list: '/exams/',
    detail: (id: string) => `/exams/${id}/`,
    publish: (id: string) => `/exams/${id}/publish/`,
    archive: (id: string) => `/exams/${id}/archive/`,
    questions: (id: string) => `/exams/${id}/questions/`,
    attempts: (id: string) => `/exams/${id}/attempts/`,
    results: (id: string) => `/exams/${id}/results/`,
  },
  questions: {
    detail: (id: string) => `/questions/${id}/`,
  },
  attempts: {
    detail: (id: string) => `/attempts/${id}/`,
    answers: (id: string) => `/attempts/${id}/answers/`,
    submit: (id: string) => `/attempts/${id}/submit/`,
    result: (id: string) => `/attempts/${id}/result/`,
  },
  analytics: {
    overview: '/analytics/overview',
    progress: '/analytics/progress',
    examResults: '/analytics/exam-results',
    aiUsage: '/analytics/ai-usage',
    export: '/analytics/export',
  },
  ai: {
    usage: '/ai/usage',
    health: '/ai/health',
  },
} as const;
