# Generated by Django 5.1.4 on 2026-08-03 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                ("slug", models.SlugField(max_length=60, verbose_name="identificador")),
                ("code", models.CharField(blank=True, max_length=30, verbose_name="código")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                ("color", models.CharField(default="#1976d2", max_length=9)),
                ("icon", models.CharField(default="apps", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Activo"), ("ARCHIVED", "Archivado")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
                "db_table": "projects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Responsable"),
                            ("EDITOR", "Editor"),
                            ("VIEWER", "Lector"),
                        ],
                        default="EDITOR",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_members",
            },
        ),
        migrations.CreateModel(
            name="VectorCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index_path", models.CharField(max_length=500)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("dimension", models.PositiveIntegerField(default=0)),
                ("vector_count", models.PositiveIntegerField(default=0)),
                ("index_type", models.CharField(default="FlatIP", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("READY", "Listo"),
                            ("REBUILDING", "Reconstruyendo"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("last_rebuilt_at", models.DateTimeField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_collection",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "colección vectorial",
                "verbose_name_plural": "colecciones vectoriales",
                "db_table": "vector_collections",
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["company", "status"], name="idx_project_company_status"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("company", "slug"),
                name="uq_project_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="uq_project_member"
            ),
        ),
    ]
