# Generated by Django 5.1.4 on 2026-08-03 22:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("trainings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=250)),
                ("summary", models.TextField(blank=True)),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("start_page", models.PositiveIntegerField(blank=True, null=True)),
                ("end_page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="trainings.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "capítulo",
                "verbose_name_plural": "capítulos",
                "db_table": "chapters",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="trainings.training",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "conversación",
                "verbose_name_plural": "conversaciones",
                "db_table": "chat_sessions",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "Usuario"),
                            ("ASSISTANT", "Asistente"),
                            ("SYSTEM", "Sistema"),
                            ("TOOL", "Herramienta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "grounded",
                    models.BooleanField(
                        default=True,
                        help_text="False cuando la IA no encontró contexto suficiente.",
                    ),
                ),
                ("needs_review", models.BooleanField(default=False)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "feedback",
                    models.SmallIntegerField(
                        blank=True, help_text="1 útil, -1 no útil.", null=True
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("heading", models.CharField(blank=True, max_length=250)),
                ("embedded", models.BooleanField(db_index=True, default=False)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chunks",
                        to="ai.chapter",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="trainings.material",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="projects.project",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "verbose_name": "fragmento",
                "verbose_name_plural": "fragmentos",
                "db_table": "chunks",
                "ordering": ["material", "index"],
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("definition", models.TextField()),
                ("relevance", models.FloatField(default=0.5)),
                ("first_mention_time", models.FloatField(blank=True, null=True)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="trainings.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto",
                "verbose_name_plural": "conceptos",
                "db_table": "concepts",
                "ordering": ["-relevance", "name"],
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="trainings.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregunta frecuente",
                "verbose_name_plural": "preguntas frecuentes",
                "db_table": "faqs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MessageCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=250)),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("score", models.FloatField(default=0)),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to="ai.chunk",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to="trainings.material",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="ai.chatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "message_citations",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="es", max_length=10)),
                ("full_text", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("confidence", models.FloatField(default=0)),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="trainings.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "transcripción",
                "verbose_name_plural": "transcripciones",
                "db_table": "transcripts",
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("text", models.TextField()),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="ai.transcript",
                    ),
                ),
            ],
            options={
                "db_table": "transcript_segments",
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("TRANSCRIPTION", "Transcripción"),
                            ("EMBEDDING", "Embeddings"),
                            ("ANALYSIS", "Análisis de material"),
                            ("CHAT", "Chat RAG"),
                            ("AGENT", "Agente tutor"),
                            ("EXAM_GENERATION", "Generación de examen"),
                            ("EXAM_GRADING", "Corrección de examen"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=120)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to="accounts.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "uso de IA",
                "verbose_name_plural": "usos de IA",
                "db_table": "ai_usage_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"], name="idx_ai_usage_company_date"
                    ),
                    models.Index(fields=["project", "purpose"], name="idx_ai_usage_project"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["material", "order"], name="idx_chapter_material"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "training", "-last_message_at"], name="idx_chat_session_user"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["session", "created_at"], name="idx_chat_message_session"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["project"], name="idx_chunk_project"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["training"], name="idx_chunk_training"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["project", "embedded"], name="idx_chunk_pending_embedding"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="idx_chunk_search_vector"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("material", "index"), name="uq_chunk_material_index"
            ),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(fields=["material", "-relevance"], name="idx_concept_material"),
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(fields=["transcript", "index"], name="idx_segment_transcript"),
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(fields=["transcript", "start_time"], name="idx_segment_start"),
        ),
        migrations.AddConstraint(
            model_name="transcriptsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gte", models.F("start_time"))),
                name="ck_segment_time_range",
            ),
        ),
    ]
