# Generated by Django 5.1.4 on 2026-08-03 22:38

import django.db.models.deletion
import src.modules.accounts.infrastructure.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(max_length=60, unique=True, verbose_name="identificador"),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=30, verbose_name="RUT / Tax ID"),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="companies/logos/")),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="correo"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="apellido"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Superadministrador"),
                            ("ADMIN", "Administrador"),
                            ("INSTRUCTOR", "Instructor"),
                            ("STUDENT", "Estudiante"),
                        ],
                        db_index=True,
                        default="STUDENT",
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=120, verbose_name="cargo")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="users/avatars/")),
                ("language", models.CharField(default="es", max_length=10)),
                ("timezone", models.CharField(default="America/Santiago", max_length=50)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "db_table": "users",
                "ordering": ["first_name", "last_name"],
            },
            managers=[
                ("objects", src.modules.accounts.infrastructure.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(db_index=True, max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("requested_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_tokens",
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="accounts.company",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="user_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo de usuarios",
                "verbose_name_plural": "grupos de usuarios",
                "db_table": "user_groups",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Inicio de sesión"),
                            ("LOGIN_FAILED", "Intento fallido"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("PASSWORD_RESET_REQUESTED", "Solicitud de recuperación"),
                            ("PASSWORD_CHANGED", "Cambio de contraseña"),
                            ("USER_CREATED", "Usuario creado"),
                            ("USER_UPDATED", "Usuario actualizado"),
                            ("USER_DEACTIVATED", "Usuario desactivado"),
                            ("ROLE_CHANGED", "Rol modificado"),
                            ("CONTENT_CREATED", "Contenido creado"),
                            ("CONTENT_DELETED", "Contenido eliminado"),
                            ("MATERIAL_UPLOADED", "Material cargado"),
                            ("EXAM_PUBLISHED", "Examen publicado"),
                            ("INDEX_REBUILT", "Índice reconstruido"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=60)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["company", "-created_at"], name="idx_audit_company_date"),
                    models.Index(fields=["entity_type", "entity_id"], name="idx_audit_entity"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["company", "is_active"], name="idx_user_company_active"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["company", "role"], name="idx_user_company_role"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["user", "used_at"], name="idx_reset_user_used"),
        ),
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uq_group_company_name"
            ),
        ),
    ]
