# Generated by Django 5.1.4 on 2026-08-03 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("trainings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveSmallIntegerField(default=0, help_text="0 = sin límite"),
                ),
                (
                    "min_progress_required",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "score_policy",
                    models.CharField(
                        choices=[
                            ("BEST", "Mejor intento"),
                            ("LAST", "Último intento"),
                            ("AVERAGE", "Promedio"),
                        ],
                        default="BEST",
                        max_length=20,
                    ),
                ),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("generated_by_ai", models.BooleanField(default=False)),
                ("generation_model", models.CharField(blank=True, max_length=120)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "verbose_name": "examen",
                "verbose_name_plural": "exámenes",
                "db_table": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "En curso"),
                            ("SUBMITTED", "Entregado"),
                            ("GRADING", "Corrigiendo"),
                            ("GRADED", "Corregido"),
                            ("EXPIRED", "Vencido"),
                        ],
                        db_index=True,
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6),
                ),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="assessments.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "intento",
                "verbose_name_plural": "intentos",
                "db_table": "attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Selección múltiple (una correcta)"),
                            ("MULTIPLE_CHOICE", "Selección múltiple (varias correctas)"),
                            ("TRUE_FALSE", "Verdadero / Falso"),
                            ("SHORT_ANSWER", "Respuesta corta"),
                            ("OPEN_ENDED", "Pregunta abierta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("statement", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Principiante"),
                            ("INTERMEDIATE", "Intermedio"),
                            ("ADVANCED", "Avanzado"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=6),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Por qué la respuesta correcta lo es."),
                ),
                (
                    "correct_text",
                    models.TextField(blank=True, help_text="Clave de respuesta corta/abierta."),
                ),
                (
                    "rubric",
                    models.JSONField(
                        blank=True, default=dict, help_text="Criterios para preguntas abiertas."
                    ),
                ),
                ("source_start_time", models.FloatField(blank=True, null=True)),
                ("source_page", models.PositiveIntegerField(blank=True, null=True)),
                ("generated_by_ai", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.exam",
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="ai.chunk",
                    ),
                ),
                (
                    "source_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="trainings.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregunta",
                "verbose_name_plural": "preguntas",
                "db_table": "questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_option_ids", models.JSONField(blank=True, default=list)),
                ("text_answer", models.TextField(blank=True)),
                (
                    "points_awarded",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
                ("review_hint", models.TextField(blank=True)),
                (
                    "grading_method",
                    models.CharField(
                        choices=[
                            ("DETERMINISTIC", "Automática exacta"),
                            ("LLM", "Evaluada por IA"),
                            ("MANUAL", "Revisión manual"),
                        ],
                        default="DETERMINISTIC",
                        max_length=20,
                    ),
                ),
                ("needs_manual_review", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "db_table": "answers",
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="Por qué esta opción es o no correcta."),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_options",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["training", "status"], name="idx_exam_training_status"),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["user", "status"], name="idx_attempt_user"),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                fields=("exam", "user", "number"), name="uq_attempt_number"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["exam", "order"], name="idx_question_exam_order"),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gt", 0)), name="ck_points_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(fields=("attempt", "question"), name="uq_answer"),
        ),
    ]
